apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{.Release.Name}}
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: {{.Release.Name}}
