apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: js-app
  namespace: arc-k8s-demo
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/akashkeshari/pipelines-javascript-docker
    ref: master
    path: charts/azure-js
  values:
    frontendServiceName: arc-k8s-demo-js