apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure_arc_sample
  namespace: arc-k8s-demo
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/Azure/arc-helm-demo
    ref: master
    path: charts/azure-arc-sample
  values:
    frontendServiceName: azure-arc-sample