apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-vote-back
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{.Release.Name}}-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: {{.Release.Name}}-vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{.Release.Name}}-vote-front
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: {{.Release.Name}}-vote-front
