name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
env:
  IMAGE_NAME: melzayet/arc-demo-app

jobs:
  test-chart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/setup-kubectl@v1
        id: installkubectl
      
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}          
        id: setcontext
        
      - uses: azure/setup-helm@v1
        id: install
      
      - name: Create Testing namespace
        run: |
          kubectl create ns candidate-$GITHUB_SHA-stg
          kubectl create ns candidate-$GITHUB_SHA-prod

      - name: Test all helm charts
        if: github.ref != 'refs/heads/master'
        run: | 
          pip install --user wheel 
          pip install --user shyaml
          cat $GITHUB_WORKSPACE/releases/stg/new-vote-app.yaml | python -m shyaml get-value spec.values >  $GITHUB_WORKSPACE/releases/stg/env-values.yaml
          helm install new-vote-app $GITHUB_WORKSPACE/charts/azure-vote/ -f $GITHUB_WORKSPACE/charts/azure-vote/values.yaml -f  $GITHUB_WORKSPACE/releases/stg/env-values.yaml -n candidate-$GITHUB_SHA-stg
          cat $GITHUB_WORKSPACE/releases/prod/new-vote-app.yaml | python -m shyaml get-value spec.values >  $GITHUB_WORKSPACE/releases/prod/env-values.yaml
          helm install new-vote-app $GITHUB_WORKSPACE/charts/azure-vote/ -f $GITHUB_WORKSPACE/charts/azure-vote/values.yaml -f  $GITHUB_WORKSPACE/releases/prod/env-values.yaml -n candidate-$GITHUB_SHA-prod

      #TODO: check kubectl wait mechanism
      - name: Sleep for 90 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '90s'

      - name: Test Service through LoadBalancer
        run: |          
          kubectl get service -l name=azure-vote-front -o=jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}' -n candidate-$GITHUB_SHA-stg > ip-stg.txt
          curl $(cat ip-stg.txt)
          kubectl get service -l name=azure-vote-front -o=jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}' -n candidate-$GITHUB_SHA-stg > ip-prod.txt          
          curl $(cat ip-prod.txt)
        
      - name: Delete Testing namespace
        run: |
          kubectl delete ns candidate-$GITHUB_SHA-stg
          kubectl delete ns candidate-$GITHUB_SHA-prod